### PR TITLE
Fix for centos6 docker run

### PR DESCRIPTION
**Pull request by rsluzhynskyy**
Currently, this cookbook does not always work with docker cento6 image.
For some reason when we install newrelic-infra on centos6 it creates upstart job - /etc/init/newrelic-infra.conf which Upstart does not pick up automatically, so we need to manually run: 

[centos@ip-10-147-84-31 ~]$ initctl reload-configuration

in order to fix this. Without this fix I am getting the following error:

* service[newrelic-infra] action enable (up to date)
    * service[newrelic-infra] action start
      
      ================================================================================
      Error executing action `start` on resource 'service[newrelic-infra]'
      ================================================================================
      
      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '1'
      ---- Begin output of /sbin/start newrelic-infra ----
      STDOUT: 
      STDERR: start: Unknown job: newrelic-infra
      ---- End output of /sbin/start newrelic-infra ----
      Ran /sbin/start newrelic-infra returned 1
      
      Cookbook Trace:
      ---------------
      /opt/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_providers/base.rb:75:in `block in action_start'
      /opt/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_providers/base.rb:136:in `notify_if_service'
      /opt/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_providers/base.rb:74:in `action_start'
      /opt/kitchen/cache/cookbooks/poise-service/files/halite_gem/poise_service/service_providers/base.rb:61:in `action_enable'
      
      Resource Declaration:
      ---------------------
      # In /opt/kitchen/cache/cookbooks/newrelic-infra/recipes/agent_linux.rb
      
       99: poise_service 'newrelic-infra' do
      100:   # TODO: Figure out how to run as a service account.
      101:   # user node['newrelic_infra']['user']['name']
      102:   command '/usr/bin/newrelic-infra ' <<
      103:           NewRelicInfra.generate_flags(node['newrelic_infra']['agent']['flags'])
      104:   options(:systemd,
      105:           template: 'newrelic-infra:default/systemd.service.erb',
      106:           after: %w(syslog.target network.target))
      107: end
      
      Compiled Resource:
      ------------------
      # Declared in /opt/kitchen/cache/cookbooks/newrelic-infra/recipes/agent_linux.rb:99:in `from_file'
      
      service("newrelic-infra") do
        provider Chef::Provider::Service::Upstart
        action [:nothing]
        default_guard_interpreter :default
        service_name "newrelic-infra"
        enabled true
        running false
        masked nil
        pattern "newrelic-infra"
        declared_type :service
        supports {:status=>true, :restart=>true, :reload=>true}
      end
      
      System Info:
      ------------
      chef_version=14.10.9
      platform=centos
      platform_version=6.10
      ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
      program_name=/opt/chef/embedded/bin/chef-client
      executable=/opt/chef/embedded/bin/chef-client

### CODE REVIEW

**Comment by rsluzhynskyy** [comment]
test this please.

**Comment by alejandrodnm** [comment]
Hi @rsluzhynskyy Thx for the PR we will review it and let you know.

**Comment by alejandrodnm** [comment]
Hi @rsluzhynskyy  I'm trying to understand your use case, you are installing the infra-agent with this chef cookbook inside a container running Centos6? If that's the case, I think a better approach is to use our official docker image for the agent https://hub.docker.com/r/newrelic/infrastructure/tags/

Also if you install the agent directly in the host it will monitor all the processes you have running, and decorate the ones running inside Docker containers with the image id and name.

**Comment by rsluzhynskyy** [comment]
Hi @alejandrodnm,

Sorry, I was not clear enough, we are trying to run your cookbook on dokken/centos-6 image and with the chef kitchen, our config:

---
provisioner:
  name: dokken

driver:
  name: dokken
  privileged: true

transport:
  name: dokken

platforms:
  - name: centos6
    driver:
      image: dokken/centos-6
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN mkdir -p /lib/modules/$(uname -r) && sudo depmod -a 2>/dev/null || true
  - name: centos7
    driver:
      image: dokken/centos-7
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN mkdir -p /lib/modules/$(uname -r) && sudo depmod -a 2>/dev/null || true

suites:
  - name: default
    run_list:
      - recipe[djif-base::default]
    verifier:
      inspec_tests:
        - compliance: admin/djif-base-inspec

verifier:
  name: inspec


It is our base cookbook and one of the dependency is newrelic-infra which fails only for dokken/centos-6 image.

**Pull request merged**
